export type MenuItem = {
  category: string;
  name: string;
  price: string;
  ingredients: string[];
  sauces: string[];
  vegan: boolean;
  glutenFree: boolean;
  togo: boolean;
  etc?: string;
  question?: string;
};

export const MENU: MenuItem[] = [
  // Appetizer (16)
  {
    category: "Appetizer",
    name: "Edamame",
    price: "$6",
    ingredients: ["soybean"],
    sauces: [],
    vegan: true,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Appetizer",
    name: "Gomae",
    price: "$6.5",
    ingredients: ["spinach"],
    sauces: ["sesame dressing"],
    vegan: true,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Appetizer",
    name: "Spring Roll(5pcs)",
    price: "$7",
    ingredients: ["veggie"],
    sauces: [],
    vegan: true,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Appetizer",
    name: "Agedashi Tofu",
    price: "$7",
    ingredients: ["deep-fried tofu"],
    sauces: ["tempura sauce"],
    vegan: true,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Appetizer",
    name: "Spicy Agedashi Tofu",
    price: "$7.5",
    ingredients: ["deep-fried tofu"],
    sauces: ["sweet spicy", "tempura sauce"],
    vegan: true,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Appetizer",
    name: "Gyoza(5pcs)",
    price: "$7",
    ingredients: ["pork"],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Appetizer",
    name: "Veggie Gyoza(5pcs)",
    price: "$7.5",
    ingredients: ["veggie"],
    sauces: [],
    vegan: true,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Appetizer",
    name: "Chicken Karaage",
    price: "$10",
    ingredients: ["deep-fried chicken"],
    sauces: ["mayo", "honey garlic sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Appetizer",
    name: "Spicy Chicken Karaage",
    price: "$10",
    ingredients: ["deep-fried chicken"],
    sauces: ["spicy mayo", "sweet spciy sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Appetizer",
    name: "Ebi Mayo",
    price: "$12",
    ingredients: ["panko-fried prawns"],
    sauces: ["spicy mayo", "unagi sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Appetizer",
    name: "Croquette(4pcs)",
    price: "$7",
    ingredients: [],
    sauces: ["mayo", "tonkatsu sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Appetizer",
    name: "Takoyaki",
    price: "$7.5",
    ingredients: ["deep-fried octopus cake"],
    sauces: ["mayo", "unagi sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Appetizer",
    name: "Rice",
    price: "$2.5",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Appetizer",
    name: "Sushi Rice",
    price: "$3",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Appetizer",
    name: "Miso Soup",
    price: "$2.5",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  // Salad (10)
  {
    category: "Salad",
    name: "Plain Sunomono",
    price: "$5",
    ingredients: [],
    sauces: [],
    vegan: true,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Salad",
    name: "Veggie Sunomono",
    price: "$5.5",
    ingredients: [],
    sauces: [],
    vegan: true,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Salad",
    name: "Ebi Sunomono",
    price: "$6",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Salad",
    name: "Tako Sunomono",
    price: "$7",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Salad",
    name: "Seaweed Salad",
    price: "$6",
    ingredients: [],
    sauces: [],
    vegan: true,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Salad",
    name: "Green Salad",
    price: "$9",
    ingredients: ["mixed greens"],
    sauces: ["house dressing"],
    vegan: true,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Salad",
    name: "Avocado Salad",
    price: "$11",
    ingredients: ["avocado", "mixed greens"],
    sauces: ["house dressing"],
    vegan: true,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Salad",
    name: "Tuna Salad",
    price: "$12.5",
    ingredients: ["tuna sashimi", "mixed greens"],
    sauces: ["house dressing"],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Salad",
    name: "Salmon Salad",
    price: "$12.5",
    ingredients: ["salmon sashimi", "mixed greens"],
    sauces: ["house dressing"],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Salad",
    name: "Sashimi Salad",
    price: "$14.5",
    ingredients: ["assorted sashimi", "mixed greens"],
    sauces: ["house dressing"],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  // Tempura (7)
  {
    category: "Tempura",
    name: "Appetizer(5pcs)",
    price: "$9.5",
    ingredients: ["prawn", "veggies"],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "2 prawn, 3 veggies",
  },
  {
    category: "Tempura",
    name: "Yam",
    price: "Half(4pcs) $6.5|Full(8pcs) $12",
    ingredients: ["Yam"],
    sauces: [],
    vegan: true,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Tempura",
    name: "Sweet Potato",
    price: "Half(4pcs) $6.5|Full(8pcs) $12",
    ingredients: ["sweet potato"],
    sauces: [],
    vegan: true,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Tempura",
    name: "Prawn",
    price: "Half(4pcs) $9|Full(8pcs) $17.5",
    ingredients: ["prawn"],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Tempura",
    name: "Veggie(6pcs)",
    price: "$9",
    ingredients: ["veggie"],
    sauces: [],
    vegan: true,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Tempura",
    name: "Yam & Prawn(8pcs)",
    price: "$14",
    ingredients: ["yam", "prawn"],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Tempura",
    name: "Assorted(10pcs)",
    price: "$15",
    ingredients: ["veggie", "prawn"],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "4 prawn, 6 veggies",
  },
  // A La Carte (6)
  {
    category: "A La Carte",
    name: "Tofu Teriyaki",
    price: "$15",
    ingredients: ["deep-fried tofu", "stir-fried veggies"],
    sauces: ["teriyaki sauce"],
    vegan: true,
    glutenFree: false,
    togo: true,
    etc: "served with miso soup & rice",
  },
  {
    category: "A La Carte",
    name: "Chicken Teriyaki",
    price: "$16",
    ingredients: ["chicken", "stir-fried veggies"],
    sauces: ["teriyaki sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "served with miso soup & rice",
  },
  {
    category: "A La Carte",
    name: "Beef Teriyaki",
    price: "$16",
    ingredients: ["beef", "stir-fried veggies"],
    sauces: ["teriyaki sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "served with miso soup & rice",
  },
  {
    category: "A La Carte",
    name: "Salmon Teriyaki",
    price: "$21",
    ingredients: ["cooked salmon", "stir-fried veggies"],
    sauces: ["teriyaki sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "served with miso soup & rice",
  },
  {
    category: "A La Carte",
    name: "Chicken Katsu",
    price: "$20",
    ingredients: ["deep-fried chicken", "salad"],
    sauces: ["tonkatsu sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "served with miso soup & rice",
  },
  {
    category: "A La Carte",
    name: "Ton Katsu",
    price: "$20",
    ingredients: ["deep-fried pork cutlet", "salad"],
    sauces: ["tonkatsu sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "served with miso soup & rice",
  },
  // Noodle - Udon(7)
  {
    category: "Udon",
    name: "Plain",
    price: "$12",
    ingredients: ["noodles", "soup"],
    sauces: [],
    vegan: true,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Udon",
    name: "Veggie",
    price: "$15",
    ingredients: ["assorted veggies", "soup"],
    sauces: [],
    vegan: true,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Udon",
    name: "Chicken",
    price: "$16",
    ingredients: ["chicken", "veggies", "soup"],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Udon",
    name: "Beef",
    price: "$16",
    ingredients: ["beef", "veggies", "soup"],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Udon",
    name: "Tempura",
    price: "$19",
    ingredients: ["tempura flakes", "veggies", "soup"],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "4pcs tempura on the side",
    question: "what kinds of tempuras? Is it possible to customize?",
  },
  {
    category: "Udon",
    name: "Seafood",
    price: "$18",
    ingredients: ["assorted seafood", "veggies", "soup"],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "메뉴판 표기 잘못된 듯",
  },
  {
    category: "Udon",
    name: "Spicy Seafood",
    price: "$19.5",
    ingredients: ["assorted seafood", "veggies", "spicy soup"],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "메뉴판 표기 잘못된 듯",
  },
  // Noodle - Ramen(4)
  {
    category: "Ramen",
    name: "Tonkotsu Chashu",
    price: "$18",
    ingredients: [
      "sliced pork belly",
      "green onion",
      "carrot",
      "bean sprouts",
      "1/2 egg",
      "pork bone broth",
    ],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Ramen",
    name: "Miso",
    price: "$18.5",
    ingredients: [
      "ground pork",
      "sliced pork belly",
      "green onion",
      "bean sprouts",
      "1/2 egg",
      "miso broth",
    ],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Ramen",
    name: "Spicy Seafood",
    price: "$21",
    ingredients: [
      "mixed seafood",
      "onion",
      "green onion",
      "bean sprouts",
      "cabbage",
      "carrot",
      "1/2 egg",
      "spicy broth",
    ],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Ramen",
    name: "Seafood Egoma",
    price: "$21",
    ingredients: [
      "ground perilla seeds",
      "green onion",
      "bean sprouts",
      "cabbage",
      "1/2 egg",
      "pork bone broth",
    ],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  // Noodle - Yakisoba(4)
  {
    category: "Yakisoba",
    name: "Veggie",
    price: "$15",
    ingredients: ["assorted veggies", "stir-fried egg noodles"],
    sauces: [],
    vegan: true,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Yakisoba",
    name: "Chicken",
    price: "$16",
    ingredients: ["chicken", "veggies", "stir-fried egg noodles"],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Yakisoba",
    name: "Beef",
    price: "$16",
    ingredients: ["beef", "veggies", "stir-fried egg noodles"],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Yakisoba",
    name: "Seafood",
    price: "$18",
    ingredients: ["assorted seafood", "veggies", "stir-fried egg noodles"],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  // Noodle - Yakiudon(4)
  {
    category: "Yakiudon",
    name: "Veggie",
    price: "$15",
    ingredients: ["assorted veggies", "stir-fried thick noodles"],
    sauces: [],
    vegan: true,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Yakiudon",
    name: "Chicken",
    price: "$16",
    ingredients: ["chicken", "veggies", "stir-fried thick noodles"],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Yakiudon",
    name: "Beef",
    price: "$16",
    ingredients: ["beef", "veggies", "stir-fried thick noodles"],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Yakiudon",
    name: "Seafood",
    price: "$18",
    ingredients: ["assorted seafood", "veggies", "stir-fried thick noodles"],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  // Oshi sushi(3)
  {
    category: "Oshi Sushi",
    name: "Salmon Oshi",
    price: "$14",
    ingredients: ["avocado(inside)", "salmon(on top)", "jalapeno(on top)"],
    sauces: ["spicy mayo", "unagi sauce", "roasted garlic seasoning"],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Oshi Sushi",
    name: "Tuna Oshi",
    price: "$14",
    ingredients: ["spicy tuna(inside)", "tuna(on top)", "garlic chips(on top)"],
    sauces: ["spicy mayo", "unagi sauce", "roasted garlic seasoning"],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Oshi Sushi",
    name: "Ebi Oshi",
    price: "$14",
    ingredients: ["ebi(on top)", "olive(on top)"],
    sauces: ["basil sauce", "cream cheese sauce", "parmesan"],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  // Donburi (13)
  {
    category: "Donburi",
    name: "Tofu Don",
    price: "$15",
    ingredients: ["deep-fried tofu on rice"],
    sauces: ["teriyaki sauce"],
    vegan: true,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Donburi",
    name: "Chicken Don",
    price: "$16",
    ingredients: ["chicken on rice"],
    sauces: ["teriyaki sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Donburi",
    name: "Beef Don",
    price: "$16",
    ingredients: ["beef on rice"],
    sauces: ["teriyaki sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Donburi",
    name: "Karaage Don",
    price: "$16",
    ingredients: ["karaage on rice"],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Donburi",
    name: "Spicy Karaage Don",
    price: "$16",
    ingredients: ["spicy karaage on rice"],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
  },
  {
    category: "Donburi",
    name: "Tuna Don",
    price: "$22",
    ingredients: ["tuna sashimi on sushi rice"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    question: "is this gluten free?",
  },
  {
    category: "Donburi",
    name: "Salmon Don",
    price: "$22",
    ingredients: ["salmon sashimi on sushi rice"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    question: "is this gluten free?",
  },
  {
    category: "Donburi",
    name: "Sockeye Salmon Don",
    price: "$28",
    ingredients: ["sockeye salmon sashimi on sushi rice"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    question: "is this gluten free?",
  },
  {
    category: "Donburi",
    name: "Tuna & Salmon Don",
    price: "$22",
    ingredients: ["sashimi on sushi rice"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    question: "is this gluten free?",
  },
  {
    category: "Donburi",
    name: "Tuna & Sockeye Don",
    price: "$26",
    ingredients: ["sashimi on sushi rice"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    question: "is this gluten free?",
  },
  {
    category: "Donburi",
    name: "Unagi Don",
    price: "$25",
    ingredients: ["unagi on sushi rice"],
    sauces: ["unagi sauce"],
    vegan: false,
    glutenFree: true,
    togo: true,
    question: "is this gluten free?",
  },
  {
    category: "Donburi",
    name: "Chirashi Don",
    price: "$31",
    ingredients: ["assorted sashimi on sushi rice"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    question: "is this gluten free?",
  },
  {
    category: "Donburi",
    name: "Spicy Chirashi Don",
    price: "$36",
    ingredients: ["assorted sashimi on rice", "lettuce"],
    sauces: ["sesame oil", "spicy sauce"],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "sushi rice 아님 주의",
    question: "is this gluten free?",
  },
  // Sashimi (15)
  {
    category: "Sashimi",
    name: "Appetizer Sashimi(4pcs)",
    price: "$10.5",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "salmon & tuna",
  },
  {
    category: "Sashimi",
    name: "Salmon",
    price: "(4pcs) $10.5|(8pcs) $20",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Sashimi",
    name: "Tuna",
    price: "(4pcs) $10.5|(8pcs) $20",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Sashimi",
    name: "Tuna & Salmon (8pcs)",
    price: "$20",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Sashimi",
    name: "Sockeye Salmon",
    price: "(4pcs) $14|(8pcs) $26",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Sashimi",
    name: "Tuna & Sockeye (8pcs)",
    price: "$24",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Sashimi",
    name: "Spicy Salmon",
    price: "(4pcs) $12|(8pcs) $22",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Sashimi",
    name: "Spicy Tuna",
    price: "(4pcs) $12|(8pcs) $22",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Sashimi",
    name: "Spicy Sockeye",
    price: "(4pcs) $16|(8pcs) $30",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Sashimi",
    name: "Toro",
    price: "(4pcs) $15|(8pcs) $28",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Sashimi",
    name: "Hamachi",
    price: "(4pcs) $15.5|(8pcs) $30",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Sashimi",
    name: "Tako",
    price: "(4pcs) $12|(8pcs) $22.5",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Sashimi",
    name: "Tuna Tadaki(8pcs)",
    price: "$22",
    ingredients: ["seared tuna"],
    sauces: ["ponzu sauce"],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Sashimi",
    name: "Assorted Sashimi(18pcs)",
    price: "$42",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  {
    category: "Sashimi",
    name: "Deluxe Assorted Sashimi(24pcs)",
    price: "$58",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
  },
  // Nigiri (26)
  {
    category: "Nigiri",
    name: "Tamago",
    price: "$2.7",
    ingredients: ["egg"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Inari",
    price: "$2.7",
    ingredients: ["bean curd"],
    sauces: [],
    vegan: true,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Avocado",
    price: "$2.7",
    ingredients: [],
    sauces: [],
    vegan: true,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Salmon",
    price: "$3",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Tuna",
    price: "$3",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Hokkigai",
    price: "$3",
    ingredients: ["surf clam"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Ebi",
    price: "$3",
    ingredients: ["cooked prawn"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Masago",
    price: "$3",
    ingredients: ["smelt roe"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Tai",
    price: "$3.2",
    ingredients: ["red snapper"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Chopped Scallop",
    price: "$3.2",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Saba",
    price: "$3.2",
    ingredients: ["mackerel"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "mackarel -> mackerel | Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Ika",
    price: "$3.2",
    ingredients: ["squid"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Tobiko",
    price: "$3.5",
    ingredients: ["flying fish roe"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Tako",
    price: "$3.5",
    ingredients: ["octopus"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Toro",
    price: "$4.3",
    ingredients: ["Tuna belly"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Sockeye",
    price: "$4.3",
    ingredients: ["wild salmon"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Unagi",
    price: "$4.3",
    ingredients: ["BBQ eel"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Hamachi",
    price: "$4.5",
    ingredients: ["yellowtail"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Hotate",
    price: "$4.5",
    ingredients: ["while scallop"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Assorted Nigiri(9pcs)",
    price: "$27.5",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Salmon Aburi",
    price: "$3.5",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Tuna Aburi",
    price: "$3.5",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Ebi Aburi",
    price: "$3.5",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Tai Aburi",
    price: "$3.7",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Sockeye Aburi",
    price: "$4.8",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  {
    category: "Nigiri",
    name: "Toro Aburi",
    price: "$4.8",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$0.5",
  },
  // Rolls (42)
  {
    category: "Rolls",
    name: "Kappa Maki",
    price: "$4",
    ingredients: ["cucumber"],
    sauces: [],
    vegan: true,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Tamago Maki",
    price: "$4",
    ingredients: ["egg"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Oshinko Maki",
    price: "$4",
    ingredients: ["Japanese pickled radish"],
    sauces: [],
    vegan: true,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Avocado Maki",
    price: "$4",
    ingredients: [],
    sauces: [],
    vegan: true,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Gomae Maki",
    price: "$5",
    ingredients: ["spinach"],
    sauces: ["sesame sauce"],
    vegan: true,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Tuna Maki",
    price: "$5",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Salmon Maki",
    price: "$5",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Ebi Maki",
    price: "$5",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Sockeye Maki",
    price: "$6",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Smoked Salmon Maki",
    price: "$6",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Negihama Maki",
    price: "$6.5",
    ingredients: ["green onions", "hamachi"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Negitoro Maki",
    price: "$6",
    ingredients: ["green onions", "tuna belly"],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Califonia Roll",
    price: "$6",
    ingredients: ["crabmeat", "avocado", "cucumber"],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Dynamite Roll",
    price: "$8",
    ingredients: [
      "prawn",
      "sweet potato tempura",
      "crabmeat",
      "avocado",
      "cucumber",
    ],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "하단 가격 표기 오류 | Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Deep Fried Cali Roll",
    price: "$8",
    ingredients: ["crabmeat", "avocado", "cucumber"],
    sauces: ["spicy mayo", "unagi sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Avocado Roll",
    price: "$6",
    ingredients: [],
    sauces: [],
    vegan: true,
    glutenFree: true,
    togo: true,
    etc: "가격 표기 오류 | Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Avocado & Cucumber Roll",
    price: "$6",
    ingredients: [],
    sauces: [],
    vegan: true,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Avocado & Yam Roll",
    price: "$6",
    ingredients: [],
    sauces: [],
    vegan: true,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Avocado & Mango Roll",
    price: "$6",
    ingredients: [],
    sauces: [],
    vegan: true,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Avocado & Cheese Roll",
    price: "$6",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$1.5",
    question: "is this gluten free?",
  },
  {
    category: "Rolls",
    name: "Avocado & Bacon Roll",
    price: "$8",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$1.5",
    question: "is this gluten free?",
  },
  {
    category: "Rolls",
    name: "Salmon & Avocado Roll",
    price: "$8",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Tuna & Avocado Roll",
    price: "$8",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: true,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Yam Roll",
    price: "$7",
    ingredients: ["yam tempura", "cucumber"],
    sauces: [],
    vegan: true,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Spicy Tuna Roll",
    price: "$8",
    ingredients: ["spicy tuna", "cucumber"],
    sauces: ["spicy mayo", "spicy sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Spicy Tuna Crunch Roll",
    price: "$9",
    ingredients: ["tempura flakes", "spicy tuna", "cucumber"],
    sauces: ["spicy mayo", "spicy sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Spicy Salmon Roll",
    price: "$8",
    ingredients: ["salmon", "cucumber"],
    sauces: ["spicy mayo", "spicy sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Spicy Salmon Crunch Roll",
    price: "$9",
    ingredients: ["tempura flakes", "salmon", "cucumber"],
    sauces: ["spicy mayo", "spicy sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Spicy Tofu Roll",
    price: "$8",
    ingredients: ["deep-fried tofu", "avocado", "cucumber"],
    sauces: ["sriracha", "sweet spicy sauce"],
    vegan: true,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Spicy Chopped Scallop Roll",
    price: "$7.5",
    ingredients: ["chopped scallop", "cucumber"],
    sauces: ["spicy mayo", "spicy sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Chopped Scallop Roll",
    price: "$7.5",
    ingredients: ["chopped scallop", "cucumber"],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Salmon & Cheese Roll",
    price: "$8",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Salmon & Mango Roll",
    price: "$8",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Unagi Roll",
    price: "$9",
    ingredients: ["cucumber", "BBQ eel"],
    sauces: ["unagi sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Mango & Cheese Roll",
    price: "$6",
    ingredients: [],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Chicken Roll",
    price: "$8",
    ingredients: ["chicken", "cucumber"],
    sauces: ["unagi sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Beef Roll",
    price: "$8",
    ingredients: ["beef", "cucumber"],
    sauces: ["unagi sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "BC Roll",
    price: "$8",
    ingredients: ["salmon tempura", "cucumber"],
    sauces: ["unagi sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Veggie Roll",
    price: "$7",
    ingredients: [
      "avocado",
      "cucumber",
      "lettuce",
      "radish",
      "oshinko",
      "beet",
    ],
    sauces: [],
    vegan: true,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "House Roll",
    price: "$11",
    ingredients: [
      "salmon",
      "tuna",
      "ebi",
      "tamago",
      "crabmeat",
      "avocado",
      "cucumber",
      "masago(on top)",
    ],
    sauces: [],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Spider Roll",
    price: "$14",
    ingredients: [
      "soft shell crab",
      "crabmeat",
      "avocado",
      "cucumber",
      "tobiko(on top)",
    ],
    sauces: ["unagi sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  {
    category: "Rolls",
    name: "Crispy Dynamite Roll",
    price: "$11.5",
    ingredients: [
      "prawn tempura",
      "crabmeat",
      "avocado",
      "cucumber",
      "sweet potato tempura(on top)",
      "potato flakes(on top)",
    ],
    sauces: ["spicy mayo", "teriyaki sauce"],
    vegan: false,
    glutenFree: false,
    togo: true,
    etc: "Brown Rice +$1.5",
  },
  // TOGO 메뉴 기준 1페이지 작성 완료
];
